class CustomError1(Exception):

    def __init__(self):
        super().__init__("Error numero 1")


class CustomError2(Exception):

    def __init__(self):
        super().__init__("Error numero 2")


class CustomError3(Exception):

    def __init__(self):
        super().__init__("Error numero 3")
